CREATE TABLE [Stage].[EdiInventoryUpdates]
(
	  [InventoryPositionId] 	VARCHAR(255)		NULL
	, [OrderTypeCD]				VARCHAR(255)		NULL
	, [SalesOrderNUM]			VARCHAR(255)		NULL
	, [SaledOrderItemNUM] 		VARCHAR(255)		NULL
	, [SaledOrderItemLineNUM] 	VARCHAR(255)		NULL
	, [KeyAccountCD] 			VARCHAR(255) 		NULL
	, [MaterialID] 				VARCHAR(255) 		NULL
	, [PlantID] 				VARCHAR(255) 		NULL
	, [SoldToCustomerID] 		VARCHAR(255) 		NULL
	, [ShipToCustomerID] 		VARCHAR(255) 		NULL
	, [MarkForCD] 				VARCHAR(255) 		NULL
	, [CalendarDTS]				DATE				NULL
	, [CalendarDateKEY]			INT					NULL
	, [DisributionChannel] 		VARCHAR(255) 		NULL
	, [RegionCD] 				VARCHAR(255) 		NULL
	, [OpenQTY]					INT					NULL 
	, [ConfirmedQTY]			INT					NULL
	, [DeliveredQTY]			INT					NULL
	, [CancelledQTY]			INT					NULL
	, [TrackingNUM]				VARCHAR(255) 		NULL
	, [Segment]					VARCHAR(255) 		NULL
	, [Season] 					VARCHAR(255) 		NULL
	, [SeasonYear]    			VARCHAR(255) 		NULL 
	, [ReasonCD]				VARCHAR(255) 		NULL
	, [OrderQuantityAMT]		INT					NULL
	, [OrderDTS]				DATE				NULL
	, [OrderDateKEY] 			INT					NULL
	, [Material]				VARCHAR(255)		NOT NULL	
	, [HeaderUniqueID]			VARCHAR(255)		NULL
	, [EdiDetailId]				VARCHAR(255)		NULL
	, [MaterialNUM]				VARCHAR(255)		NULL
	, [ActivityCD]				VARCHAR(255)		NULL
	, [LegacyMaterialNUM]		VARCHAR(255)		NULL		
	, [UniversalProductCD]		VARCHAR(255)		NOT NULL
	, [UnitOfMeasure]			VARCHAR(255)		NULL
	, [ItemDTS]					VARCHAR(255)		NULL
	, [ItemNUM]					VARCHAR(255)		NULL
	, [QuantityAMT]				VARCHAR(255)		NULL
	, [ItemPrice]				DATE				NULL
	, [ItemQualifierCD]			INT					NULL
	, [ObjectNUM]				VARCHAR(255)		NULL
	, [Katr7]					VARCHAR(255)		NULL
	, [DocumentDTS]				VARCHAR(255)		NULL
	, [LegacyStoreNUM]			INT					NULL
	, [InternalNUM] 			INT					NULL
	, [RefDoc]					INT					NULL
	, [DocNUM]					INT					NULL
	, [PosNUM]					VARCHAR(255)		NULL
	, [PartnerID]				VARCHAR(255)		NULL
	, [SoldTo]					VARCHAR(255)		NULL
	, [LegacySoldTo]			VARCHAR(255)		NULL
	, [JurisdictionCD]			VARCHAR(255)		NULL
	, [NameText]				INT					NULL
	, [DamagedQTY]				INT					NULL
	, [DaysSupplyQTY]			INT					NULL
	, [ForecastVarianceQTY]		INT					NULL
	, [OnHoldQTY]				INT					NULL
	, [AvailableQTY]			INT					NULL
	, [EndingQTY]				INT					NULL
	, [InTransitQTY]			INT					NULL
	, [OutOfStockQTY]			INT					NULL
	, [OnOrderQTY]				INT					NULL
	, [ReceivedQTY]				INT					NULL
	, [SoldQTY]					INT					NULL
	, [InventoryAdjustmentQTY]	INT					NULL
	, [ReturnedQTY]				INT					NULL
	, [SalesQTY]				INT					NULL
	, [SellThruPCT]				INT					NULL
	, [TotalSalesQTY]			INT					NULL
	, [WeeksSupplyNUM]			INT					NULL
	, [EdiFileSentDTS]			DATE				NULL
	, [EdiFileSentKEY]			INT					NULL
	, [EdiFileStartDTS]			DATE				NULL
	, [EdiFileStartKEY]			INT					NULL
	, [EdiFileEndDTS]			DATE				NULL
	, [EdiFileEndKEY]			INT					NULL

)